### PR TITLE
add different device ID

### PR DESCRIPTION
**Pull request by dertobias**
RuntimeError Exception prohibits code to proceed.
Tested with (apds)GY-9960 board.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@dertobias could you modify the code to print the value of `self._read8(_APDS9960_ID)` on your device? It sounds to me like your device is some sort of variation that has a different ID.

I think it would be best if we added a new ID to a list of valid IDs to check rather than removing the logic to check them entirely.

**Comment by dertobias** [comment]
you're right. it prints 168. So adding it as device_id2 0xa8 worked on my end :)

**Comment by FoamyGuy** [comment]
@dertobias If you're up to it can you change this PR (or submit a new one) to refactor DEVICE_ID to be a list or tuple and then have the logic use something  `if self._read8(_APDS9960_ID) not in DEVICE_IDS:`

**Comment by dertobias** [comment]
@FoamyGuy patch works for me :)

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thanks for the addition @dertobias!

I tested this successfully on a CLUE

**Pull request merged**
